const casaRoyal = [
    {
        id:"0",
        img:"https://images1.apartments.com/i2/9z8-vVK9o3eZsjZhho6rUMknTnuB43q64-z1lR4nB1I/111/grove-at-162nd-vancouver-wa-foto-principal.jpg?p=1",
        type:"House",
        status:"For rent",
        location:"Vancouver",
        direction:"16331 NE 21st St, Vancouver WA 98684",
        area:"3200 Sq Ft.",
        price:"1,000.000",
        parking:"2",
        bathroom:"2",
        bedroom:"4",
        owner:"Enrique Pinzon",
        phone:"3093181",
        date:"2 weeks ago",
        description:"The house is unique, you should buy it!"
    
    },
    {
        'id':'1',
        'img':'https://images1.apartments.com/i2/66tZVSJJuc6NoQSQDqZyDnjT5pagXZFfoLnivMdIKWo/116/16009-ne-30th-st-vancouver-wa-foto-del-edificio.jpg?p=1',
        'type':'House',
        'status':'Sale',
        'location':'Toronto',
        'direction':'16009 NE 30th St Parkway',
        'area':'2900 Sq Ft.',
        'price':'800.000',
        'parking':'1',
        'bathroom':'2',
        'bedroom':'3',
        'owner':'Enrique Pinzon',
        'phone':'3093181',
        'date':'3 months ago',
        'description':'The house is unique, you should buy it!'
    
    },
    {
        'id':'2',
        'img':'https://media-cdn.tripadvisor.com/media/vr-splice-j/00/17/9b/1b.jpg',
        'type':'House',
        'status':'For rent',
        'location':'Sídney',
        'direction':'Strathfield,Homebush Road 1/3',
        'area':'4100 Sq Ft.',
        'price':'2,500.000',
        'parking':'2',
        'bathroom':'4',
        'bedroom':'6',
        'owner':'Enrique Pinzon',
        'phone':'3093181',
        'date':'01 days ago',
        'description':'The house is unique, you should buy it!'
    
    },
    {
        'id':'3',
        'img':'https://media-cdn.tripadvisor.com/media/vr-ha-splice-j/0d/36/3c/1f.jpg',
        'type':'Apartment',
        'status':'For rent',
        'location':'Melbourne',
        'direction':'Murray Street Pyrmont NSW 2009',
        'area':'1900 Sq Ft.',
        'price':'900.000',
        'parking':'1',
        'bathroom':'1',
        'bedroom':'2',
        'owner':'Enrique Pinzon',
        'phone':'3093181',
        'date':'10 days ago',
        'description':'The apartment is unique, you should buy it!'
    
    },
    {
        'id':'4',
        'img':'https://cdn.realestateview.com.au/images/listing/2-bedroom-apartment-in-richmond-vic-3121/1440-w/14422824-1-A8D3DE0.jpg',
        'type':'Apartment',
        'status':'Sale',
        'location':'Sevilla',
        'direction':'802/2 McGoun Street, Richmond',
        'area':'3000 Sq Ft.',
        'price':'1,700.000',
        'parking':'1',
        'bathroom':'2',
        'bedroom':'3',
        'owner':'Enrique Pinzon',
        'phone':'3093181',
        'date':'15 days ago',
        'description':'The apartment is unique, you should buy it!'
    
    },
    {
        'id':'5',
        'img':'https://images1.apartments.com/i2/WIGVyyGZ_qtLdM92A9wKyNU02SqWJ4l5PNaWW9FnvFM/116/10104-ne-hazel-dell-ave-vancouver-wa-foto-del-edificio.jpg?p=1',
        'type':'House',
        'status':'For rent',
        'location':'Vancouver',
        'direction':'10104 NE Hazel Dell Ave',
        'area':'3200 Sq Ft.',
        'price':'1,150.000',
        'parking':'2',
        'bathroom':'2',
        'bedroom':'4',
        'owner':'Enrique Pinzon',
        'phone':'3093181',
        'date':'21 days ago',
        'description':'The house is unique, you should buy it!'
    
    },
    {
        'id':'6',
        'img':'https://media-cdn.tripadvisor.com/media/vr-splice-j/00/58/ff/4f.jpg',
        'type':'Apartment',
        'status':'For rent',
        'location':'Toronto',
        'direction':'4104 Downtonw gran Victorian',
        'area':'1700 Sq Ft.',
        'price':'650.000',
        'parking':'0',
        'bathroom':'1',
        'bedroom':'2',
        'owner':'Enrique Pinzon',
        'phone':'3093181',
        'date':'27 days ago',
        'description':'The apartment is unique, you should buy it!'
    
    },
    {
        'id':'7',
        'img':'https://media-cdn.tripadvisor.com/media/vr-ha-splice-j/0c/fc/80/ab.jpg',
        'type':'Apartment',
        'status':'For rent',
        'location':'Sídney',
        'direction':'231 Terrace Heritage',
        'area':'1520 Sq Ft.',
        'price':'450.000',
        'parking':'0',
        'bathroom':'2',
        'bedroom':'2',
        'owner':'Enrique Pinzon',
        'phone':'3093181',
        'date':'11 days ago',
        'description':'The apartment is unique, you should buy it!'
    
    },
    {
        'id':'8',
        'img':'https://cdn.realestateview.com.au/images/listing/2-bedroom-apartment-in-bentleigh-vic-3204/1440-w/14196711-1-6F34DB4.jpg',
        'type':'Apartment',
        'status':'Sale',
        'location':'Melbourne',
        'direction':'Bent Street, Bentleigh, VIC 3204',
        'area':'3220 Sq Ft.',
        'price':'1,100.000',
        'parking':'1',
        'bathroom':'2',
        'bedroom':'4',
        'owner':'Enrique Pinzon',
        'phone':'3093181',
        'date':'2 months ago',
        'description':'The apartment is unique, you should buy it!'
    
    },
    {
        'id':'9',
        'img':'https://images1.apartments.com/i2/GiHPmfCV5hJcQmeC5SyM6Wm3kQ4iomSev80sH1ffsxc/111/2718-nw-118th-cir-vancouver-wa-foto-principal.jpg?p=1',
        'type':'House',
        'status':'Sale',
        'location':'Sevilla',
        'direction':'2718 NW 118th Cir Felida',
        'area':'4220 Sq Ft.',
        'price':'2,330.000',
        'parking':'1',
        'bathroom':'3',
        'bedroom':'5',
        'owner':'Enrique Pinzon',
        'phone':'3093181',
        'date':'1 month ago',
        'description':'The house is unique, you should buy it!'
    
    },
    {
        'id':'10',
        'img':'https://media-cdn.tripadvisor.com/media/vr-ha-splice-j/10/19/cc/19.jpg',
        'type':'House',
        'status':'For rent',
        'location':'Vancouver',
        'direction':'Log House by the Lake, Luxury Retreat',
        'area':'3050 Sq Ft.',
        'price':'7,225.000',
        'parking':'4',
        'bathroom':'4',
        'bedroom':'7',
        'owner':'Enrique Pinzon',
        'phone':'3093181',
        'date':'6 months ago',
        'description':'The house is unique, you should buy it!'
    
    },
    {
        'id':'11',
        'img':'https://media-cdn.tripadvisor.com/media/vr-ha-splice-j/0f/d1/05/a1.jpg',
        'type':'Apartment',
        'status':'For rent',
        'location':'Toronto',
        'direction':'1748 NW 68th Ver Tida',
        'area':'3050 Sq Ft.',
        'price':'225.000',
        'parking':'0',
        'bathroom':'1',
        'bedroom':'2',
        'owner':'Enrique Pinzon',
        'phone':'3093181',
        'date':'4 months ago',
        'description':'The apartment is unique, you should buy it!'
    
    },
    {
        'id':'12',
        'img':'https://media-cdn.tripadvisor.com/media/vr-splice-j/00/33/98/2d.jpg',
        'type':'House',
        'status':'For rent',
        'location':'Sídney',
        'direction':'G11/380 Queensberry St North ',
        'area':'4550 Sq Ft.',
        'price':'1,483.200',
        'parking':'3',
        'bathroom':'4',
        'bedroom':'7',
        'owner':'Enrique Pinzon',
        'phone':'3093181',
        'date':'a year ago',
        'description':'The house is unique, you should buy it!'
    
    },
    {
        'id':'13',
        'img':'https://images1.apartments.com/i2/b-nWMIJOfOxGGB9JOL7L8HXlzs8rtllqWU2AxH3TPH8/111/7410-ne-54th-cir-vancouver-wa-foto-principal.jpg?p=1',
        'type':'House',
        'status':'Sale',
        'location':'Melbourne',
        'direction':'F13/480 Queensberry St South ',
        'area':'4550 Sq Ft.',
        'price':'4,613.400',
        'parking':'2',
        'bathroom':'3',
        'bedroom':'5',
        'owner':'Enrique Pinzon',
        'phone':'3093181',
        'date':'07 days ago' ,
        'description':'The house is unique, you should buy it!'
    
    },
    {
        'id':'14',
        'img':'https://media-cdn.tripadvisor.com/media/vr-ha-splice-j/0f/c0/ce/fa.jpg',
        'type':'Apartment',
        'status':'For Rent',
        'location':'Sevilla',
        'direction':'AD12 Bloor West Village Gem',
        'area':'3190 Sq Ft.',
        'price':'1,903.400',
        'parking':'3',
        'bathroom':'3',
        'bedroom':'5',
        'owner':'Enrique Pinzon',
        'phone':'3093181',
        'date':'18 days ago' ,
        'description':'The apartment is unique, you should buy it!'
    
    }

]

